name: publish

on:
  push:
    paths-ignore:
      - "docker-compose.yaml"

jobs:
  publish-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            docker: linux/amd64
            cross: false
          - target: aarch64-unknown-linux-gnu
            docker: linux/arm64
            cross: true
    steps:
      - uses: actions/checkout@v2
      - name: Setup cargo cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
          key: ${{ runner.os }}-${{ matrix.target }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.target }}-cargo-
      - name: install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: ${{ matrix.cross }}
      - name: compile
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=${{ matrix.target }}
      - name: move target
        run: |
          mkdir release && mv target/${{ matrix.target }}/release/naive release/
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: docker build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: ${{ matrix.docker }}
          push: true
          tags: |
            ghcr.io/boringbay/naive
